version: '3.1'

services:
  elasticsearch:
    image: elasticsearch
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
        # https://github.com/docker-library/elasticsearch/issues/111
        # uliimit
  kibana:
      image: kibana
      ports:
          - 5601:5601